backend:
  name: github
  repo: conormcafee/sweeney-todd-barbers
  branch: master

media_folder: static/assets
public_folder: assets

collections: 
 -  label: "Page"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}