backend:
  name: github
  repo: conormcafee/sweeney-todd-barbers
  branch: master

media_folder: static/assets
public_folder: assets

collections: 
 -  label: "Page"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "site/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Prices"
        name: "prices"
        file: "site/content/prices.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Price List"
        name: "priceList"
        file: "site/content/priceList.md"
        widget: list
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Price, name: price, widget: markdown}
