backend:
  name: github
  repo: conormcafee/sweeney-todd-barbers
  branch: master

media_folder: static/assets
public_folder: assets

collections: 
 -  label: "Page"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "site/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Prices"
        name: "prices"
        file: "site/content/prices.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Testimonials"
        name: "testimonials"
        file: "site/content/testimonials.md"
        widget: "list"
        fields:
          - label: Testimonial
            name: testimonial
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Message, name: message, widget: string}
