backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections: 
 -  label: "Homepage"
    name: "homepage"
    files:
      - label: "About"
        name: "about"
        file: "site/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: "Featured Image",
            name: "thumbnail",
            widget: "image",
            default: null}
      - label: "Prices"
        name: "prices"
        file: "site/content/prices.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Price List
            name: priceList
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Price, name: price, widget: string}
      - label: "Testimonials"
        name: "testimonials"
        file: "site/content/testimonials.md"
        fields:
          - label: Testimonial
            name: testimonial
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Message, name: message, widget: string}
      - label: "Opening Hours"
        name: "openingHours"
        file: "site/content/openingHours.md"
        fields: 
          - label: Times
            name: times
            widget: list
            fields:
              - {label: Day, name: day, widget: string}
              - {label: Open, name: open, widget: string, required: false}
              - {label: Closed, name: closed, widget: string, required: false}
