backend:
  name: github
  repo: conormcafee/sweeney-todd-barbers
  branch: master

media_folder: static/assets
public_folder: assets
show_preview_links: false

collections: 
 -  label: "Homepage"
    name: "homepage"
    files:
      - label: "About"
        name: "about"
        file: "site/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Prices"
        name: "prices"
        file: "site/content/prices.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Price List
            name: priceList
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Price, name: price, widget: string}
      - label: "Testimonials"
        name: "testimonials"
        file: "site/content/testimonials.md"
        fields:
          - label: Testimonial
            name: testimonial
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Message, name: message, widget: string}
